[package]
name = "ticket-sale"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "ticket_sale"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-bpf = []

[dependencies]
anchor-lang = { version = "0.25.0", features = ["init-if-needed"] }
anchor-spl = "0.25.0"
anchor-safe-math = "0.2.1"
mpl-token-metadata = "1.2.10"
anchor-metaplex = { git = "https://github.com/Apocentre/anchor-metaplex", version = "0.4.1" }
common = { path = "../../common" }
ticket-nft = { path = "../ticket-nft", features = ["cpi"] }

[dev-dependencies]
solana-program-test = "1.8.0"
solana-sdk = "1.9.5"
solana-test-utils = { git = "https://github.com/Apocentre/solana-test-utils", version = "0.2.21" }
test-context = "0.1.3"
common-test = { path = "../../common-test" }
